#############################################################################
# File name:	Makefile
# Author:		Kailani Pinon
# Date:			10..2020
# Class:		CS 300
# Assignment:	Generic Dynamic Queue
# Purpose:		This file defines terminal-friendly actions for the
#				GenericDynamicQ
#############################################################################

CC=gcc
CFLAGS=-Wall -g

.PHONY: all clean

all: bin bin/queuedriver

bin:
	mkdir -p bin
	
#executable and dependencies

#driver object and dependencies

#dependencies objects

#rebuild list and priority queue

#valgrind for memory leak debugging

#zipping (tarball)

#clean